language: generic 
sudo: required
services:
    - docker

before_install:
    # -t means tag
    - docker build -t xkong93/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true xkong93/react-test npm test

after_success:
    - docker build -t xkong93/multi-client ./client
    - docker build -t xkong93/multi-nginx ./nginx
    - docker build -t xkong93/multi-server ./server
    - docker build -t xkong93/multi-worker ./worker
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    - docker push xkong93/multi-client
    - docker push xkong93/multi-nginx
    - docker push xkong93/multi-server
    - docker push xkong93/multi-worker